CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=y
# CONFIG_DONGLE_SCREEN_LIGHT_SENSOR_BH1750=y